spring:
  application:
    name: keycloak

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/demo-keycloak
  datasource:
    username: keycloak
    url: jdbc:postgresql://localhost:5432/keycloak
    password: keycloak@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8999